apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-starter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-starter
  template:
    metadata:
      labels:
        app: hackathon-starter
    spec:
      containers:
        - name: hackathon-starter
          image: 590183766587.dkr.ecr.us-west-2.amazonaws.com/node-js-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-starter-service
spec:
  type: LoadBalancer
  selector:
    app: hackathon-starter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
